class Question < ActiveRecord::Base
	MINISTRIES = [
		"Agriculture", 
		"Chemicals and Fertilizers", 
		"Civil Aviation", 
		"Coal", 
		"Commerce and Industry", 
		"Communications and Information Technology", 
		"Consumer Affairs, Food and Public Distribution", 
		"Corporate Affairs", 
		"Culture", 
		"Defence", 
		"Development of North Eastern Region", 
		"Drinking Water Supply and Sanitation", 
		"Earth Sciences", 
		"Environment, Forest and Climate Change", 
		"External Affairs", 
		"Finance", 
		"Food Processing Industries", 
		"Health and Family Welfare", 
		"Heavy Industries and Public Enterprises", 
		"Home Affairs", 
		"Housing and Urban Poverty Alleviation", 
		"Human Resource Development", 
		"Information and Broadcasting", 
		"Labour and Employment", 
		"Law and Justice", 
		"Micro, Small and Medium Enterprises", 
		"Mines", 
		"Minority Affairs", 
		"New and Renewable Energy", 
		"Overseas Indian Affairs", 
		"Panchayati Raj", 
		"Parliamentary Affairs", 
		"Personnel, Public Grievances and Pensions", 
		"Petroleum and Natural Gas", 
		"Planning", 
		"Power", 
		"Railways", 
		"Road Transport and Highways", 
		"Rural Development", 
		"Science and Technology", 
		"Shipping", 
		"Skill Development and Entrepreneurship", 
		"Social Justice and Empowerment", 
		"Statistics and Programme Implementation", 
		"Steel", 
		"Textiles", 
		"Tourism", 
		"Tribal Affairs", 
		"Urban Development", 
		"Water Resources", 
		"Women and Child Development", 
		"Youth Affairs and Sports"
	].freeze

	STATUSES = {
		deferred: 'DEFERRED',
		answered: 'ANSWERED',
		scheduled: 'SCHEDULED',
		rejected: 'REJECTED',
		waiting: 'WAITING'
	}.freeze
	
end
